### ISSUE TITLE
Feedback on dephell docker

### ISSUE THREAD

**Issue by orsinium** [UnitedIncome/json-syntax#18]
I see you're using `dephell docker` commands. That's cool! This is a quite new feature, and it definitely isn't powerful enough yet. Obviously, it should have deps installation logic, at least. Is something else? What is your feedback? What do you like to see in dephell what isn't implemented yet? Thanks :)

I'm dephell author, BTW. So, it's not just curiosity, it's a roadmap building ;)

**Comment by bsamuel-ui** [comment]
I have been meaning to give you an answer here for ages, but alas, the project works for what we're doing and I haven't had a great cause to test new stuff with it. I do want to make sure it's working with the latest versions of Python and when I get to that, I'll take a look at what I'm doing with dephell. At this point, honestly, I forget how I set it up.

**Comment by orsinium** [comment]
Got it, thank you :)
